version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:8080"
  log1:
    image: isaeme23/logservice:latest
    container_name: log1
    ports:
      - "34001:34001"
  log2:
    image: isaeme23/logservice:latest
    container_name: log2
    ports:
      - "34002:34002"
  log3:
    image: isaeme23/logservice:latest
    container_name: log3
    ports:
      - "34003:34003"
  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: